name: CI - Playwright Cucumber TS Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest  # Using Ubuntu, which works well with Playwright Docker images

    env:
      NODE_ENV: "ci"
      NAME: ${{ secrets.NAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Playwright Docker Image
        run: |
          docker pull mcr.microsoft.com/playwright:v1.20.0-focal  # Ensure the image is pulled before use

      - name: Install dependencies and run tests in Playwright Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace mcr.microsoft.com/playwright:v1.20.0-focal npm ci  # Install dependencies inside Docker container
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace mcr.microsoft.com/playwright:v1.20.0-focal npm run test  # Run tests inside Docker container

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 14
