name: CI - Playwright Cucumber TS Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu for Docker, since Playwright Docker images are based on Ubuntu

    env:
      NODE_ENV: "ci"
      NAME: ${{ secrets.NAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Ensures Docker is set up properly for multi-platform support

      - name: Build and run Playwright Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace mcr.microsoft.com/playwright:v1.56.1-noble npm ci  # Install dependencies inside Docker container
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace mcr.microsoft.com/playwright:v1.56.1-noble npm run test  # Run tests inside Docker container

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 14
